### PR TITLE
Add support for Windows SPTI

### PR DESCRIPTION
**Pull request by ab932**
Hi Tal,

I've added SCSI Pass Through Interface (SPTI) support to iSCSI Console to access a remote tape device from my development VM. I need some help with ISCSIConsole/MainForm.cs. I didn't know exactly how to pass the OnLogEntry event to the SPTITarget class... I'm no expert in C#!

Looking forward to any comments!
Alex

### CODE REVIEW

**Comment by TalAloni** [comment]
Hi Alex,
That's very interesting, I actually have a SCSI HBA that I was hoping to team with iSCSI Console one day.
1. Regarding OnLogEntry , You can use "if (target is VirtualSCSITarget)" to check the type.
2. It's not clear to me why the SPTIDisk class is needed.
3. In ExecuteCommand, I'm seeing that your are accessing "ExpectedDataTransferLength" of the *iSCSI* PDU. that's a shortcut that you shouldn't take.
The SCSI layer should execute *SCSI* commands, and should only utilize information given in that command. ExpectedDataTransferLength is part of the higher-level iSCSI layer, and your "optimization" violates the iSCSI design and (I think) may even return incorrect results in some cases.

Feel free to contact me by email ( tal.aloni.il@gmail.com ) and let me know how I can help completing the implementation. It would be great to have physical disk support as well.
Tal

**Comment by TalAloni** [comment]
Regarding the UI:
Don't you think it makes more sense to add an "Add SPTI Target" button to the main form?
(This also makes the SPTIDevice class unnecessary).

**Comment by ab932** [comment]
1) Ok, will do.
2) I'm not sure if SPTIDisk is needed anymore, good catch.
3) I've got to read through it again but maybe I don't need to use the iSCSI PDU directly.

In regards to the UI, I see your point... I'll try it out. Might take me a few days to put up another commit.

Thanks!
Alex

**Comment by TalAloni** [comment]
Hi Alex,
- Check out my latest commit, I have added DeviceInterfaceUtils.GetDeviceList method that returns a list of DeviceInfo so now you can easily access the DeviceName in addition to the DevicePath, this should make the GUI more friendly.

- I have added the MediumChangerClassGuid and the StoragePortClassGuid to DeviceInterfaceUtils, the latter will list storage controllers, including SCSI HBAs. It seems to me that the TapeClassGuid is not needed for the proposed implementation.

- in SPTITarget.cs (line 119) please use "uint size", instead of "var size" to maintain C# 2.0 compatibility.

Let me know if I can help in any way. Can't wait to test on my HBA.

**Comment by TalAloni** [comment]
Please send me an email to we can collaborate more closely on this.

**Comment by ab932** [comment]
Hey Tal,

I'm offline for the weekend but totally will follow up on Monday.

Alex

**Pull request closed without merging**
